M48
; DRILL file {KiCad 8.0.1} date 2024-07-17T22:41:00+1000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-17T22:41:00+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X5.7219Y-1.7843
X5.9128Y-1.7843
T2
X5.71Y-1.665
X5.9246Y-1.665
M30
